
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from "@/components/ui/toaster"



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextDraw',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {





  return (
    <html lang="en" className='overflow-hidden  '>
    
      <body className='{inter.className}' >
        

        {children}
        <Toaster />
        </body>
    </html>
  )
}
